version: 1
groups:
  code-review:
    approve_by_comment:
      approve_regex: ^Approved
      enabled: true
      reject_regex: ^Rejected
    required: 1
    reset_on_push:
      enabled: true
    users:
    - felipemantoan
    - alantavares
    - jhoncf
    - luiscera
    conditions:
      branches:
        - "main..."
      files:
        exclude:
          - ".pullapprove.yml"

  admin:
    approve_by_comment:
      approve_regex: ^Approved
      enabled: true
      reject_regex: ^Rejected
    required: 1
    reset_on_push:
      enabled: true
    users:
    - felipemantoan
    - alantavares
    - jhoncf
    - luiscera
    conditions:
      files:
        - ".pullapprove.yml"
